name: Bash

on:
  push:

permissions:
  id-token: write

jobs:
  bash:
    runs-on: ubuntu-24.04
    steps:
    - name: scratchpad
      run: |-
        env | grep ID_TOKEN

    - name: Authenticate to AWS using Github OIDC
      run: |-
        curl \
          --verbose \
          --header "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          $ACTIONS_ID_TOKEN_REQUEST_URL