name: Bash

on:
  push:

permissions:
  id-token: write

env:
  ROLE_ARN: arn:aws:iam::471112677734:role/ExerciseGithubOidc

jobs:
  bash:
    runs-on: ubuntu-24.04
    steps:
    - name: scratchpad
      run: |-
        env | grep ID_TOKEN

    - name: Authenticate to AWS using Github OIDC
      run: |-
        curl \
          --verbose \
          --header "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          $ACTIONS_ID_TOKEN_REQUEST_URL \
        | jq -r .value > /tmp/id_token

        cat /tmp/id_token | base64 -d
    
    - name: Use the ID token to authenticate to AWS
      run: |-
        aws sts assume-role-with-web-identity \
          --role-arn $ROLE_ARN \
          --role-session-name GitHubActions \
          --web-identity-token $(cat /tmp/id_token)