name: Proof of Concept

on:
  push:

permissions:
  id-token: write

env:
  ROLE_ARN: arn:aws:iam::471112677734:role/ExerciseGithubOidc
  REGION: us-east-2

jobs:

  # Actions-based solution
  actions:
    runs-on: ubuntu-24.04
    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ env.ROLE_ARN }}
        aws-region: us-east-2

  # Bash-based solution
  bash:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: .github/scripts/bash.sh
